"""
Andy Bloch's starting hand ranges for tournaments.
These are measured by position, and we can translate this to a dictionary where the key is the
number of seats off the button the position is. The button is 0 seats from the button.
"""

# Pre-ante ranges
preante = {
    0: ('22', '33', '44', '55', '66', '77', '88', '99', 'TT', 'JJ', 'QQ', 'KK', 'AA',
        'A2', 'A3', 'A4', 'A5', 'A6', 'A7', 'A8', 'A9', 'AT', 'AJ', 'AQ', 'AK',
        'A2s', 'A3s', 'A4s', 'A5s', 'A6s', 'A7s', 'A8s', 'A9s', 'ATs', 'AJs', 'AQs', 'AKs',
        'K7', 'K8', 'K9', 'KT', 'KJ', 'KQ',
        'K2s', 'K3s', 'K4s', 'K5s', 'K6s', 'K7s', 'K8s', 'K9s', 'KTs', 'KJs', 'KQs', 'KKs',
        'Q9', 'QT', 'QJ',
        'Q5s', 'Q6s', 'Q7s', 'Q8s', 'Q9s', 'QTs', 'QJs',
        'J9', 'JT',
        'J6s', 'J7s', 'J8s', 'J9s', 'JTs',
        'T8', 'T9',
        'T6s', 'T7s', 'T8s', 'T9s',
        '98',
        '96s', '97s', '98s',
        '85s', '86s', '87s',
        '75s', '76s',
        '64s', '65s',
        '54s',
        ),

    1: ('22', '33', '44', '55', '66', '77', '88', '99', 'TT', 'JJ', 'QQ', 'KK', 'AA',
        'A4', 'A5', 'A6', 'A7', 'A8', 'A9', 'AT', 'AJ', 'AQ', 'AK',
        'A2s', 'A3s', 'A4s', 'A5s', 'A6s', 'A7s', 'A8s', 'A9s', 'ATs', 'AJs', 'AQs', 'AKs',
        'KT', 'KJ', 'KQ',
        'K5s', 'K6s', 'K7s', 'K8s', 'K9s', 'KTs', 'KJs', 'KQs', 'KKs',
        'QT', 'QJ',
        'Q8s', 'Q9s', 'QTs', 'QJs',
        'JT',
        'J7s', 'J8s', 'J9s', 'JTs',
        'T9',
        'T7s', 'T8s', 'T9s',
        '97s', '98s',
        '87s',
        '76s',
        ),

    2: ('22', '33', '44', '55', '66', '77', '88', '99', 'TT', 'JJ', 'QQ', 'KK', 'AA',
        'A8', 'A9', 'AT', 'AJ', 'AQ', 'AK',
        'A2s', 'A3s', 'A4s', 'A5s', 'A6s', 'A7s', 'A8s', 'A9s', 'ATs', 'AJs', 'AQs', 'AKs',
        'KJ', 'KQ',
        'K7s', 'K8s', 'K9s', 'KTs', 'KJs', 'KQs', 'KKs',
        'QT', 'QJ',
        'Q8s', 'Q9s', 'QTs', 'QJs',
        'J8s', 'J9s', 'JTs',
        'T8s', 'T9s',
        '98s',
        '87s',
        ),

    3: ('22', '33', '44', '55', '66', '77', '88', '99', 'TT', 'JJ', 'QQ', 'KK', 'AA',
        'AT', 'AJ', 'AQ', 'AK',
        'A3s', 'A4s', 'A5s', 'A6s', 'A7s', 'A8s', 'A9s', 'ATs', 'AJs', 'AQs', 'AKs',
        'KJ', 'KQ',
        'K8s', 'K9s', 'KTs', 'KJs', 'KQs', 'KKs',
        'QJ',
        'Q8s', 'Q9s', 'QTs', 'QJs',
        'J9s', 'JTs',
        'T8s', 'T9s',
        '98s',
        ),

    4: ('33', '44', '55', '66', '77', '88', '99', 'TT', 'JJ', 'QQ', 'KK', 'AA',
        'AT', 'AJ', 'AQ', 'AK',
        'A8s', 'A9s', 'ATs', 'AJs', 'AQs', 'AKs',
        'KJ', 'KQ',
        'K9s', 'KTs', 'KJs', 'KQs', 'KKs',
        'Q9s', 'QTs', 'QJs',
        'J9s', 'JTs',
        'T9s',
        ),

    5: ('44', '55', '66', '77', '88', '99', 'TT', 'JJ', 'QQ', 'KK', 'AA',
        'AJ', 'AQ', 'AK',
        'A8s', 'A9s', 'ATs', 'AJs', 'AQs', 'AKs',
        'KQ',
        'K9s', 'KTs', 'KJs', 'KQs', 'KKs',
        'Q9s', 'QTs', 'QJs',
        'J9s', 'JTs',
        'T9s',
        ),

    6: ('55', '66', '77', '88', '99', 'TT', 'JJ', 'QQ', 'KK', 'AA',
        'AJ', 'AQ', 'AK',
        'A9s', 'ATs', 'AJs', 'AQs', 'AKs',
        'KQ',
        'KTs', 'KJs', 'KQs', 'KKs',
        'QTs', 'QJs',
        'JTs',
        ),
}


# Post-ante ranges
postante = {
    0: (),
    1: (),
    2: (),
    3: (),
    4: (),
    5: (),
    6: (),
}
